### ISSUE TITLE
docker run is not working on linux 

### ISSUE THREAD

**Issue by rohitssalyan** [khadkakrishna/kepler-gl-docker#1]
`standard_init_linux.go:228: exec user process caused: exec format error`

A "multi-arch" Python interpreter built on MacOS is intended to target MacOS-on-Intel and MacOS-on-Apple's-arm64.

There is absolutely no binary compatibility with Linux-on-Apple's-arm64, or with Linux-on-aarch64. You can't run MacOS executables on Linux, whether the architecture matches.

Docker images built on mac will not work on Linux operating system.

**Comment by khadkakrishna** [comment]
Fixed it, added image for both linux/arm64 and linux/amd64
